#!/usr/bin/env python3
"""Install a separately scoped HTTPS capability for the single-user native app.

The secret stays in a root-only file; no public listener or broad API proxy is
created. Companion capabilities keep their existing, narrower permissions.
"""
import fcntl
import os
from pathlib import Path
import re
import subprocess
import tempfile

CAPABILITY = re.compile(r'petrarca-mobile-[0-9a-f]{64}')
ID = r'[A-Za-z0-9_:%.-]+'
# Explicit native-app routes. Administrative/bulk-ingest routes are not exposed.
GET = [
    r'study/(status|summary)',
    r'health', r'api/(?:manifest|articles-meta|knowledge-index|clusters|syntheses)',
    rf'api/articles/{ID}/content', r'book/resurfacing/status',
    rf'book/(?:research|prescan)/{ID}',
    r'curriculum/(?:list|entity-index|graph-data)',
    rf'curriculum/book-context/{ID}', rf'curriculum/review/timeline/{ID}',
    rf'curriculum/{ID}', r'entities', rf'entity/{ID}',
    r'review/(?:queue|stats|elicit-candidates|voice-elicit-check)',
    r'kindle/(?:browse|library|recently-started|highlights)',
    r'stats/(?:native|dashboard|dashboard-data)',
    r'knowledge/sweep/domains', rf'knowledge/sweep/(?:plan|history)/{ID}',
    rf'knowledge/profile/{ID}', r'notes', r'defender/sessions',
    rf'defender/sessions/{ID}', r'commonplace/events', rf'projects/{ID}',
]
POST = [
    r'study/(?:session|event|voice)',
    r'feedback', r'log/events',
    r'book/(?:identify|ocr-toc|ocr-page|upload-photo|photo-results|voice-note|research|chapter-insights|story-so-far|process-kindle)',
    r'book/resurfacing/(?:generate|respond|skip)',
    r'curriculum/review/(?:generate|result|suspend)',
    r'curriculum/knowledge/(?:update|import-assessment)',
    r'curriculum/elicit/(?:start|respond)',
    r'review/(?:microlearning|ml-flag-inaccurate|also-want-to-know|targeted-quiz|create-factual-quiz|suspend-fact|book-complete|chapter-complete|chapter-context|generate-question|answer|explore|voice-memo|voice-elicit|elicit-know-nothing|hamarquizen|hamarquizen-cross)',
    r'review/microlearning/dismiss', r'review/follow-up/(?:trigger|generate)',
    r'structural/grade', r'entity/(?:tap|questions|research|notes)',
    r'explore/capture', r'kindle/(?:curate|include|classify)',
    r'projects/note', rf'projects/{ID}/update',
    r'knowledge/sweep/(?:submit|gaps|transcribe)',
    r'defender/(?:start|respond|transcribe)',
    r'commonplace/(?:resurface|resurface-audio)', rf'notes/{ID}/execute-action',
]
BOTH = [r'book/sync', r'projects']


def render(capability: str) -> str:
    if not CAPABILITY.fullmatch(capability):
        raise ValueError('Invalid mobile API capability format')
    blocks = ['# Generated by install_mobile_api.py; contains a private capability.']
    for method, routes in [('GET POST', BOTH), ('POST', POST), ('GET', GET)]:
        for route in routes:
            blocks.append(f'''location ~ ^/{capability}/(?<mobile_route>{route})$ {{
    access_log off;
    error_log /dev/null crit;
    limit_except {method} {{ deny all; }}
    client_max_body_size 26m;
    client_body_timeout 30s;
    proxy_connect_timeout 5s;
    proxy_read_timeout 240s;
    proxy_send_timeout 240s;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8090/$mobile_route$is_args$args;
}}''')
    # Regex locations above must precede this prefix's normal fallback. Do not
    # use ^~, which would suppress the allowlist regexes entirely.
    blocks.append(f'''location /{capability}/ {{
    access_log off;
    error_log /dev/null crit;
    return 404;
}}''')
    return '\n\n'.join(blocks) + '\n'


def atomic_write(path: Path, payload: bytes, mode: int) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.mobile-api-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as out:
            os.fchmod(out.fileno(), mode)
            out.write(payload)
            out.flush()
            os.fsync(out.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def install() -> None:
    if os.geteuid() != 0:
        raise SystemExit('Run the mobile API installer as root')
    secret = Path('/etc/petrarca-mobile-capability')
    if secret.is_symlink() or not secret.is_file():
        raise SystemExit('A regular root-only mobile capability file is required')
    stat = secret.stat()
    if stat.st_uid != 0 or stat.st_gid != 0 or stat.st_mode & 0o777 != 0o600:
        raise SystemExit('Mobile capability must be root:root mode 0600')
    snippet = Path('/etc/nginx/snippets/petrarca-mobile-api.conf')
    site = Path('/etc/nginx/sites-available/petrarca-expo-ssl')
    if snippet.is_symlink() or site.is_symlink():
        raise SystemExit('Refusing symlinked nginx destinations')
    with open('/run/lock/petrarca-mobile-api.lock', 'w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        old_site = site.read_bytes()
        old_snippet = snippet.read_bytes() if snippet.exists() else None
        mode = site.stat().st_mode & 0o777
        include = b'    include /etc/nginx/snippets/petrarca-mobile-api.conf;'
        new_site = old_site
        if include not in old_site.splitlines():
            closing = old_site.rfind(b'\n}')
            if closing < 0:
                raise SystemExit('Cannot find HTTPS server closing brace')
            new_site = old_site[:closing] + b'\n' + include + old_site[closing:]
        rendered = render(secret.read_text().strip()).encode()
        try:
            atomic_write(snippet, rendered, 0o600)
            atomic_write(site, new_site, mode)
            # nginx errors may contain the capability: retain only exit status.
            subprocess.run(['nginx', '-t'], capture_output=True, check=True)
            subprocess.run(['systemctl', 'reload', 'nginx'], capture_output=True, check=True)
        except Exception:
            atomic_write(site, old_site, mode)
            if old_snippet is None:
                snippet.unlink(missing_ok=True)
            else:
                atomic_write(snippet, old_snippet, 0o600)
            subprocess.run(['nginx', '-t'], capture_output=True, check=True)
            subprocess.run(['systemctl', 'reload', 'nginx'], capture_output=True, check=True)
            raise SystemExit('Mobile API installation failed; prior nginx configuration restored') from None
    print('Private mobile HTTPS route installed; research server remains loopback-only.')


if __name__ == '__main__':
    install()
